### ISSUE TITLE
Rom module may not be working as intended.

### ISSUE THREAD

**Issue by prozacgod** [MightyPirates/TIS-3D#73] opened 2017-09-26 20:28 UTC
I wrote a bunch of code to fill a ram module, then right clicked that module with a rom module, then placed the rom module in a new controller/casing setup and read back zeros from all of the bytes I accessed.

I installed nbtedit to verify that the modules memory is all zeros after clicking to clone

MC 1.12.1
FORGE 14.22.1.2478

The mods installed are ComputerCraft and Tis3D so I don't think it's something esoteric

**Comment by fnuecke** [comment] 2017-09-27 07:59
Hmm, can't reproduce this, neither via copy through sneak-clicking, nor the new memory editor UI. Could you check if you still see this in [the latest dev build](http://ci.cil.li/job/TIS-3D-MC1.12/), and if so provide me with more detailed steps to reproduce? Thanks.

**Comment by prozacgod** [comment] 2017-09-27 14:49
Can confirm, steps to reproduce.... be me, be dumb, somehow don't do it correctly....

:/

**Comment by fnuecke** [comment] 2017-09-27 17:24
Heh, been there. I'll close this then :)

**Closed as completed by fnuecke** 2017-09-27 17:24 UTC

**Comment by OwOday** [comment] 2024-10-17 21:23
I have this issue :/
